### PR TITLE
Migrate to ES Modules

### PR DESCRIPTION
**Pull request by 59naga**
Since I want to use your library from `.mjs` or `babel`, I use the one that adjusted the environment and released it as named-package [`@59naga/assert-diff`](https://unpkg.com/@59naga/assert-diff@1.2.8/).

```bash
yarn add -D eastern @59naga/assert-diff
node --experimental-modules test/index.mjs
#  ✓  strict diff deep equal (3 ms)
#
#  Eastern: 1 passing (21 ms)
```

This can be used as follows for `.mjs` or` babel`.

```js
// test/index.mjs
import spec from 'eastern'
import { deepEqual } from '@59naga/assert-diff'

spec('strict diff deep equal', () => {
  deepEqual({a: 1}, {a: 1}, 'this should not fail')
})
```

`.default` is required as a disadvantage for commonjs.

```js
var assert = require('@59naga/assert-diff').default
assert.deepEqual({a: 1}, {a: 1}, 'this should not fail')
```

### CODE REVIEW

**Comment by pihvi** [comment]
Thank you!

I released this as new major version 2.0.0. Can you confirm this is now working for you?

-Antti

**Comment by 59naga** [comment]
Oh sorry, You need to run `npm build` before` npm publish` to [generate code `index.js` for babel and commonjs](https://unpkg.com/@59naga/assert-diff@1.2.8/lib/) :100:.

```bash
yarn add -D eastern assert-diff

# work!
node --experimental-modules test/index.mjs

# doesn't work...
node test/index.js
```

```js
var assert = require('assert-diff').default // Error: Cannot find module 'assert-diff'
assert.deepEqual({a: 1}, {a: 1}, 'this should not fail')
```

**Comment by pihvi** [comment]
Right, thanks!

I have no idea of these new module exports or babel builds, so I'm very grateful for the help :)

I got the tests working now with mocha which is familiar to me. I have to look at that eastern module a bit more to understand it. But now the build is published in v. 2.0.1. Is this working for you?

**Comment by pihvi** [comment]
I restored the old index.js on the side of the index.mjs as the new code broke the old behavior promised by this library i.e. it is a drop-in replacement for package 'assert'. So by default it should work the same as 'assert'. Now it won't work for e.g. assert(true), but you must use assert.default(true) etc. so it's not a drop-in replacement anymore. Do you have an idea how the module exports could work in the new system as before so assert(true) could work without having to use require('assert-diff').default ?

**Comment by 59naga** [comment]
Awesome, that works! :+1:
If you continue to use mocha please see [@std/esm](https://github.com/mochajs/mocha/issues/3006#issuecomment-368366438)

**Pull request merged**
